### ISSUE TITLE
ПР4 (ломаная линия)

### ISSUE THREAD

**Issue by drxaos** [usmetanina/java-repos#1]
1. readCoordinates() и readPolyline() - в джаве обычно для перевода объекта в строку служит метод toString. Если код перевода не делает ничего "тяжелого" (типа обращения к файлам или к бд), то лучше переопределить им стандартный toString().
2. Аналогично вместо compare() лучше переопределить стандартный equals().
3. Output.outputTops, судя по названию, ответственен за вывод на экран, а на самом деле выполняет еще и функцию ввода точки. Нужно переделать методы в Input и Output, чтобы каждый класс занимался своим делом.

**Comment by usmetanina** [comment]
поправила a7b0a16cd3c799463b18cdd179d1ce63285f24de

**Comment by drxaos** [comment]
принято
